//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_Id { get; set; }
        public System.DateTime Create_Date { get; set; }
        public int Pacient_Id { get; set; }
        public int Service_Id { get; set; }
        public Nullable<bool> Order_Status { get; set; }
        public Nullable<System.DateTime> Complete_Time { get; set; }
        public Nullable<int> BarCode { get; set; }
    
        public virtual Pacient Pacient { get; set; }
        public virtual Service Service { get; set; }
    }
}
