//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Provided
    {
        public int Service_Provided_Id { get; set; }
        public int User_Id { get; set; }
        public int Service_Id { get; set; }
        public Nullable<System.DateTime> Date_Provided { get; set; }
        public int Analyzer_Id { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
