//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Service_Provided = new HashSet<Service_Provided>();
        }
    
        public int User_Id { get; set; }
        public string Full_Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime Last_Login_Date { get; set; }
        public int Service_Id { get; set; }
        public Nullable<int> Insurance_Company_Id { get; set; }
        public Nullable<decimal> Account { get; set; }
        public int Role_Id { get; set; }
    
        public virtual Insurance_Company Insurance_Company { get; set; }
        public virtual Role Role { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Provided> Service_Provided { get; set; }
    }
}
